baseurl = "https://golangleipzig.space" # baseurl = "https://golang-leipzig.github.io/"
title = "Leipzig Gophers"
languageCode = "en-us"
theme = "simple-hugo-theme"

pygmentsCodefences = true
pygmentsCodeFencesGuessSyntax = true
# pygmentsoptions = "linenos=table"
pygmentsStyle = "github"

paginate = 256 # we do not have a db

[menu]
  [[menu.main]]
    url = "/posts/"
    name = "blog"
    weight = 1

  [[menu.footer]]
    url = "https://www.meetup.com/Leipzig-Golang/"
    name = "Meetup"
    weight = 1
  [[menu.footer]]
    url = "https://github.com/golang-leipzig"
    name = "GitHub"
    weight = 3
  [[menu.footer]]
    url = "https://raw.githubusercontent.com/golang-leipzig/golang-leipzig.github.io/source/Impressum.txt"
    name = "Impressum"
    weight = 4
  [[menu.footer]]
    url = "https://golangleipzig.space/qr.png"
    name = "QR"
    weight = 5
  [[menu.footer]]
    url = "https://1mb.club/"
    name = "1MB"
    weight = 6
