baseurl = "https://golang-leipzig.github.io/"
title = "Go and Cloud Native Leipzig"
languageCode = "en-us"
theme = "simple-hugo-theme"

pygmentsCodefences = true
pygmentsCodeFencesGuessSyntax = true
# pygmentsoptions = "linenos=table"
pygmentsStyle = "github"

paginate = 30

[menu]
  [[menu.main]]
    url = "/posts/"
    name = "blog"
    weight = 1

  [[menu.footer]]
    url = "https://www.meetup.com/Leipzig-Golang-and-Cloud/"
    name = "Meetup"
    weight = 1
  [[menu.footer]]
    url = "https://twitter.com/golang_leipzig"
    name = "Twitter"
    weight = 2
  [[menu.footer]]
    url = "https://github.com/golang-leipzig"
    name = "GitHub"
    weight = 3
  [[menu.footer]]
    url = "https://raw.githubusercontent.com/golang-leipzig/golang-leipzig.github.io/source/Impressum.txt"
    name = "Impressum"
    weight = 4
