name: broken links

on:
  push:
    branches:
      - source

jobs:
  broken-links:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: false
      - name: Check for broken links
        id: brokenLinks
        uses: lycheeverse/lychee-action@master
        with:
          args: --user-agent "golangleipzig.space" --exclude meet.google.com content/
      - name: Create Issue From File
        if: github.repository_owner == 'golang-leipzig' && failure() && steps.brokenLinks.outcome == 'failure'
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Broken Links Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
