ollama run gemma4:latest 'in python; write depth-first search; style: beginner; only output the code'
ollama run gemma4:latest 'in python; write depth-first search; style: expert; only output the code'
ollama run gemma4:latest 'in python; write depth-first search; style: compact; only output the code'
